SET local check_function_bodies = off;

CREATE EXTENSION "pgjwt" SCHEMA "extensions";

CREATE EXTENSION "postgis" SCHEMA "public";

CREATE TABLE "public"."comments" (
  "id"         uuid                     NOT NULL DEFAULT extensions.uuid_generate_v4(),
  "post_id"    uuid                     NOT NULL,
  "user_id"    uuid                     NOT NULL,
  "content"    text                     NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  CONSTRAINT "comments_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."comments"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."global_chat" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "email"      character varying        NOT NULL DEFAULT ''::character varying,
  "body"       character varying        NOT NULL DEFAULT ''::character varying,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "global_chat_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."global_chat"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."post_likes" (
  "id"         uuid                     NOT NULL DEFAULT extensions.uuid_generate_v4(),
  "post_id"    uuid                     NOT NULL,
  "user_id"    uuid                     NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  CONSTRAINT "post_likes_pkey" PRIMARY KEY (id),
  CONSTRAINT "post_likes_post_id_user_id_key" UNIQUE (post_id, user_id)
);

ALTER TABLE "public"."post_likes"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."posts" (
  "id"          uuid                        NOT NULL DEFAULT extensions.uuid_generate_v4(),
  "user_id"     uuid                        NOT NULL,
  "route_name"  text                        NOT NULL,
  "start_point" text                        NOT NULL,
  "end_point"   text                        NOT NULL,
  "start_geom"  public.geometry(Point,4326),
  "end_geom"    public.geometry(Point,4326),
  "duration"    interval                    NOT NULL,
  "rating"      numeric(2,1),
  "description" text,
  "image_url"   text,
  "created_at"  timestamp with time zone    DEFAULT now(),
  "route_type"  text,
  CONSTRAINT "posts_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."posts"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."routes" (
  "id"           uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "user_id"      uuid                     NOT NULL,
  "name"         text                     NOT NULL,
  "description"  text,
  "data"         jsonb                    NOT NULL,
  "distance_km"  numeric,
  "duration_min" numeric,
  "is_public"    boolean                  DEFAULT false,
  "created_at"   timestamp with time zone DEFAULT now(),
  "updated_at"   timestamp with time zone DEFAULT now(),
  CONSTRAINT "routes_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."routes"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."user_bikes" (
  "id"         uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "brand"      text                     NOT NULL,
  "model"      text                     NOT NULL,
  "year"       smallint                 NOT NULL,
  "color"      text                     NOT NULL,
  "photo_url"  text                     NOT NULL,
  "is_active"  boolean                  NOT NULL DEFAULT false,
  "created_at" timestamp with time zone DEFAULT now(),
  CONSTRAINT "user_bikes_brand_check" CHECK ((char_length(brand) <= 40)),
  CONSTRAINT "user_bikes_color_check" CHECK ((char_length(color) <= 20)),
  CONSTRAINT "user_bikes_model_check" CHECK ((char_length(model) <= 40)),
  CONSTRAINT "user_bikes_pkey" PRIMARY KEY (id),
  CONSTRAINT "user_bikes_year_check" CHECK (((year >= 1900) AND ((year)::double precision <= (date_part('year'::text, now()) + (1)::double precision)))),
  "user_id"    uuid                     DEFAULT auth.uid()
);

ALTER TABLE "public"."user_bikes"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."user_profiles" (
  "id"             uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "first_name"     text,
  "last_name"      text,
  "bio"            text,
  "avatar_url"     text,
  "created_at"     timestamp with time zone NOT NULL DEFAULT now(),
  "email"          text,
  "active_bike_id" uuid,
  CONSTRAINT "user_profiles_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."user_profiles"
  ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.like_post (
  p_post_id uuid
)
  RETURNS void
  LANGUAGE plpgsql
  AS $function$
begin
  insert into post_likes(post_id, user_id)
  values (p_post_id, auth.uid())
  on conflict do nothing;
end
$function$;

CREATE OR REPLACE FUNCTION public.set_updated_at()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.unlike_post (
  p_post_id uuid
)
  RETURNS void
  LANGUAGE plpgsql
  AS $function$
begin
  delete from post_likes
  where post_id = p_post_id
    and user_id = auth.uid();
end
$function$;

ALTER TABLE "public"."comments"
  ADD CONSTRAINT "comments_post_id_fkey" FOREIGN KEY (post_id) REFERENCES public.posts(id) ON DELETE CASCADE;

ALTER TABLE "public"."post_likes"
  ADD CONSTRAINT "post_likes_post_id_fkey" FOREIGN KEY (post_id) REFERENCES public.posts(id) ON DELETE CASCADE;

ALTER TABLE "public"."routes"
  ADD CONSTRAINT "routes_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."user_profiles"
  ADD CONSTRAINT "user_profiles_active_bike_id_fkey" FOREIGN KEY (active_bike_id) REFERENCES public.user_bikes(id);

ALTER TABLE "public"."user_profiles"
  ADD CONSTRAINT "user_profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id);

ALTER TABLE "public"."comments"
  ADD CONSTRAINT "comments_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE;

ALTER TABLE "public"."post_likes"
  ADD CONSTRAINT "post_likes_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE;

ALTER TABLE "public"."posts"
  ADD CONSTRAINT "posts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE;

CREATE VIEW "public"."post_comment_counts" AS  SELECT comments.post_id,
    count(*) AS comments
   FROM public.comments
  GROUP BY comments.post_id;

CREATE VIEW "public"."post_like_counts" AS  SELECT post_likes.post_id,
    count(*) AS likes
   FROM public.post_likes
  GROUP BY post_likes.post_id;

CREATE INDEX comments_post_idx ON public.comments USING btree (post_id);

CREATE INDEX comments_user_idx ON public.comments USING btree (user_id);

CREATE INDEX post_likes_post_idx ON public.post_likes USING btree (post_id);

CREATE INDEX post_likes_user_idx ON public.post_likes USING btree (user_id);

CREATE INDEX posts_created_idx ON public.posts USING btree (created_at DESC);

CREATE INDEX posts_user_idx ON public.posts USING btree (user_id);

CREATE INDEX profiles_active_bike_idx ON public.user_profiles USING btree (active_bike_id);

CREATE INDEX routes_created_idx ON public.routes USING btree (created_at DESC);

CREATE INDEX routes_public_idx ON public.routes USING btree (is_public);

CREATE INDEX routes_user_idx ON public.routes USING btree (user_id);

CREATE TRIGGER trg_routes_updated
  BEFORE UPDATE ON public.routes
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE POLICY "Comments insert" ON "public"."comments"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((user_id = auth.uid()));

CREATE POLICY "Comments read" ON "public"."comments"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Comments update / delete" ON "public"."comments"
  FOR ALL
  TO PUBLIC
  USING ((user_id = auth.uid()));

CREATE POLICY "Enable read access for all users" ON "public"."global_chat"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Enable write access for all users" ON "public"."global_chat"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (true);

CREATE POLICY "Likes delete (unlike)" ON "public"."post_likes"
  FOR DELETE
  TO PUBLIC
  USING ((user_id = auth.uid()));

CREATE POLICY "Likes insert" ON "public"."post_likes"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((user_id = auth.uid()));

CREATE POLICY "Likes read" ON "public"."post_likes"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Posts insert" ON "public"."posts"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((user_id = auth.uid()));

CREATE POLICY "Posts read" ON "public"."posts"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Posts update / delete" ON "public"."posts"
  FOR ALL
  TO PUBLIC
  USING ((user_id = auth.uid()));

CREATE POLICY "insert owns route" ON "public"."routes"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "owner full access" ON "public"."routes"
  FOR ALL
  TO PUBLIC
  USING ((auth.uid() = user_id))
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "read public routes" ON "public"."routes"
  FOR SELECT
  TO PUBLIC
  USING ((is_public = true));

CREATE POLICY "Enable delete for users based on user_id" ON "public"."user_profiles"
  FOR DELETE
  TO "authenticated"
  USING ((auth.uid() = id));

CREATE POLICY "Enable insert for authenticated users only" ON "public"."user_profiles"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((auth.uid() = id));

CREATE POLICY "Enable read access for all users" ON "public"."user_profiles"
  FOR SELECT
  TO "authenticated"
  USING (true);

CREATE POLICY "update by id" ON "public"."user_profiles"
  FOR UPDATE
  TO "authenticated"
  USING ((auth.uid() = id))
  WITH CHECK ((auth.uid() = id));

CREATE POLICY "user can set active bike" ON "public"."user_profiles"
  FOR UPDATE
  TO PUBLIC
  USING ((id = auth.uid()))
  WITH CHECK ((id = auth.uid()));

CREATE POLICY "Give users access to own folder 1oj01fe_0" ON "storage"."objects"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (((bucket_id = 'avatars'::text) AND (( SELECT (auth.uid())::text AS uid) = (storage.foldername(name))[1])));

CREATE POLICY "Give users access to own folder 1oj01fe_1" ON "storage"."objects"
  FOR UPDATE
  TO PUBLIC
  USING (((bucket_id = 'avatars'::text) AND (( SELECT (auth.uid())::text AS uid) = (storage.foldername(name))[1])));

CREATE POLICY "Give users access to own folder 1oj01fe_2" ON "storage"."objects"
  FOR DELETE
  TO PUBLIC
  USING (((bucket_id = 'avatars'::text) AND (( SELECT (auth.uid())::text AS uid) = (storage.foldername(name))[1])));

CREATE POLICY "Give users access to own folder 1oj01fe_3" ON "storage"."objects"
  FOR SELECT
  TO PUBLIC
  USING (((bucket_id = 'avatars'::text) AND (( SELECT (auth.uid())::text AS uid) = (storage.foldername(name))[1])));

CREATE POLICY "posts_delete 1rma4z_0" ON "storage"."objects"
  FOR DELETE
  TO "authenticated"
  USING ((bucket_id = 'posts'::text));

CREATE POLICY "posts_insert 1rma4z_0" ON "storage"."objects"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((bucket_id = 'posts'::text));

CREATE POLICY "posts_select 1rma4z_0" ON "storage"."objects"
  FOR SELECT
  TO "authenticated"
  USING ((bucket_id = 'posts'::text));

CREATE POLICY "posts_update 1rma4z_0" ON "storage"."objects"
  FOR UPDATE
  TO "authenticated"
  USING ((bucket_id = 'posts'::text));

CREATE POLICY "bikes_delete_own_folder" ON "storage"."objects"
  FOR DELETE
  TO PUBLIC
  USING (((bucket_id = 'bikes'::text) AND (name ~~ (auth.uid() || '/%'::text))));

CREATE POLICY "bikes_insert_own_folder" ON "storage"."objects"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (((bucket_id = 'bikes'::text) AND (name ~~ (auth.uid() || '/%'::text))));

CREATE POLICY "bikes_select_authenticated" ON "storage"."objects"
  FOR SELECT
  TO PUBLIC
  USING (((bucket_id = 'bikes'::text) AND (auth.role() = 'authenticated'::text)));

CREATE POLICY "bikes_update_own_folder" ON "storage"."objects"
  FOR UPDATE
  TO PUBLIC
  USING (((bucket_id = 'bikes'::text) AND (name ~~ (auth.uid() || '/%'::text))));

ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."comments";

ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."global_chat";

COMMENT ON EXTENSION "pgjwt" IS 'JSON Web Token API for Postgresql';

COMMENT ON EXTENSION "postgis" IS 'PostGIS geometry and geography spatial types and functions';

GRANT EXECUTE ON FUNCTION "public"."like_post"(uuid) TO PUBLIC, "anon", "authenticated";

REVOKE ALL ON FUNCTION "public"."like_post"(uuid) FROM "postgres";

GRANT EXECUTE ON FUNCTION "public"."like_post"(uuid) TO "postgres";

GRANT EXECUTE ON FUNCTION "public"."like_post"(uuid) TO "service_role";

GRANT EXECUTE ON FUNCTION "public"."set_updated_at"() TO PUBLIC, "anon", "authenticated";

REVOKE ALL ON FUNCTION "public"."set_updated_at"() FROM "postgres";

GRANT EXECUTE ON FUNCTION "public"."set_updated_at"() TO "postgres";

GRANT EXECUTE ON FUNCTION "public"."set_updated_at"() TO "service_role";

GRANT EXECUTE ON FUNCTION "public"."unlike_post"(uuid) TO PUBLIC, "anon", "authenticated";

REVOKE ALL ON FUNCTION "public"."unlike_post"(uuid) FROM "postgres";

GRANT EXECUTE ON FUNCTION "public"."unlike_post"(uuid) TO "postgres";

GRANT EXECUTE ON FUNCTION "public"."unlike_post"(uuid) TO "service_role";

REVOKE ALL ON SEQUENCE "public"."global_chat_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."global_chat_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."global_chat_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."global_chat_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."global_chat_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."global_chat_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."global_chat_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."global_chat_id_seq" TO "service_role";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."comments" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."comments" FROM "postgres";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."comments" TO "postgres";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."comments" TO "service_role";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."global_chat" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."global_chat" FROM "postgres";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."global_chat" TO "postgres";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."global_chat" TO "service_role";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."post_likes" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."post_likes" FROM "postgres";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."post_likes" TO "postgres";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."post_likes" TO "service_role";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."posts" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."posts" FROM "postgres";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."posts" TO "postgres";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."posts" TO "service_role";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."routes" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."routes" FROM "postgres";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."routes" TO "postgres";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."routes" TO "service_role";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_bikes" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."user_bikes" FROM "postgres";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_bikes" TO "postgres";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_bikes" TO "service_role";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_profiles" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."user_profiles" FROM "postgres";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_profiles" TO "postgres";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_profiles" TO "service_role";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."post_comment_counts" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."post_comment_counts" FROM "postgres";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."post_comment_counts" TO "postgres";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."post_comment_counts" TO "service_role";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."post_like_counts" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."post_like_counts" FROM "postgres";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."post_like_counts" TO "postgres";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."post_like_counts" TO "service_role";

ALTER TABLE "public"."user_bikes"
  ADD CONSTRAINT "user_bikes_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

CREATE UNIQUE INDEX user_bikes_active_uniq ON public.user_bikes USING btree (user_id)
  WHERE (is_active = true);

CREATE INDEX user_bikes_user_idx ON public.user_bikes USING btree (user_id);

CREATE POLICY "limit 5 bikes" ON "public"."user_bikes"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((( SELECT count(*) AS count
   FROM public.user_bikes b
  WHERE (b.user_id = auth.uid())) < 5));

CREATE POLICY "limit max 5 bikes" ON "public"."user_bikes"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((( SELECT count(*) AS count
   FROM public.user_bikes b
  WHERE (b.user_id = auth.uid())) < 5));

CREATE POLICY "own bikes read" ON "public"."user_bikes"
  FOR SELECT
  TO PUBLIC
  USING ((user_id = auth.uid()));

CREATE POLICY "own bikes write" ON "public"."user_bikes"
  FOR ALL
  TO PUBLIC
  USING ((user_id = auth.uid()))
  WITH CHECK ((user_id = auth.uid()));

